### ISSUE TITLE
Multiple units on single webapp instance

### ISSUE THREAD

**Issue by nicdive** [ael-code/daikin-control#6]
Hi,

This tool works like a charm for me. Thanks a lot for your research. Could you add the possibility of controlling several units from the same page if it's not to much work?. The best would be to select on the page one or more units to send command . I have 8 of them in my house and it would be a big improvement for me if you make it possible. 
Regards
Nicolas

**Comment by quinaz** [comment]
Anything new on this subject! I'd like also to control multiple units in a single webpage...

**Comment by ael-code** [comment]
I don't like php at all, so I've coded a [python library](https://github.com/ael-code/daikin-aricon-pylib) to control the daikin units.
The idea is to use this library as base to build more robust and hackable control interface.

At the moment there is no documentation at all, but all the basic staff should work. The problem is that I don't have so much time in this period. If there is some programmer interested in this it would be nice to work together.

**Comment by quinaz** [comment]
😒 I don't know how to use this!!! Can you give me some directions?!
